### ISSUE TITLE
Regarding of sample data (ivy20.csv in iAtlas)

### ISSUE THREAD

**Issue by hmkim** [Gibbsdavidl/Immune-Subtype-Clustering#2]
Hello, 
please check this issue.

1) iAtlas Tools — Immune Subtype Predictor (https://isb-cgc.shinyapps.io/shiny-iatlas/)
![2019-01-18 18 11 01](https://user-images.githubusercontent.com/4966343/51376833-a7e86300-1b4c-11e9-9eb7-9fd33570b228.png)

2) ipynb notebooks in github  
![2019-01-18 18 10 55](https://user-images.githubusercontent.com/4966343/51376840-ab7bea00-1b4c-11e9-9265-cbbf8793c69c.png)

Why is the difference exist in the call result ?

**Comment by Gibbsdavidl** [comment]
Do you mean (for example) the call for X305273026 between the iAtlas tool and the notebook?

I computed the scores in a different way... I think should be better, but it's still experimental.

But(!) that data set (the ivy20.csv)  was in no way normalized or prepared properly ... it was meant to just a quick way to see the format and have it run.

**Comment by Gibbsdavidl** [comment]
Looks weird though. I think this happens when the 'new data' is systemically lower overall, cluster C4 was low in all signatures. And most of the brain cancers were in C4, so seems reasonable since I think IVY was glioblastomas.

**Comment by hmkim** [comment]
@Gibbsdavidl Yes, I mean the call  between the iAtlas tool and the notebook.

so, you mean the  result  in notebook seems reasonable, right?

Thanks for your reply.
